require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'
require 'rake/gempackagetask'

require 'date'
require 'rbconfig'


task :default => :test
task :test => 'test:isolated'

## This is required until the regular test task
## below passes.  It's not ideal, but at least
## we can see the failures
namespace :test do
  task :isolated do
    dir = ENV["TEST_DIR"] || "**"
    Dir["test/#{dir}/*_test.rb"].all? do |file|
      next true if file.include?("fixtures")
      ruby = File.join(*RbConfig::CONFIG.values_at('bindir', 'RUBY_INSTALL_NAME'))
      system(ruby, '-Itest', "-I#{File.dirname(__FILE__)}/../activesupport/lib", file)
    end or raise "Failures"
  end
end

Rake::TestTask.new('test:regular') do |t|
  t.libs << 'test' << "#{File.dirname(__FILE__)}/../activesupport/lib"
  t.pattern = 'test/**/*_test.rb'
  t.warning = true
  t.verbose = true
end

# Update spinoffs -------------------------------------------------------------------

desc "Updates application README to the latest version Railties README"
task :update_readme do
  readme = "lib/rails/generators/rails/app/templates/README"
  rm readme
  cp "./README", readme
end

desc 'Generate guides (for authors), use ONLY=foo to process just "foo.textile"'
task :generate_guides do
  ENV["WARN_BROKEN_LINKS"] = "1" # authors can't disable this
  ruby "guides/rails_guides.rb"
end

task :update_prototype_ujs do
  system "curl http://github.com/rails/prototype-ujs/raw/master/src/rails.js > lib/rails/generators/rails/app/templates/public/javascripts/rails.js"
end

# Validate guides -------------------------------------------------------------------------
desc 'Validate guides, use ONLY=foo to process just "foo.html"'
task :validate_guides do
  ruby "guides/w3c_validator.rb"
end

# Generate documentation ------------------------------------------------------------------

Rake::RDocTask.new { |rdoc|
  rdoc.rdoc_dir = 'doc'
  rdoc.title    = "Railties -- Gluing the Engine to the Rails"
  rdoc.options << '--line-numbers' << '--inline-source' << '--accessor' << 'cattr_accessor=object'
  rdoc.options << '--charset' << 'utf-8'
  rdoc.template = ENV['template'] ? "#{ENV['template']}.rb" : '../doc/template/horo'
  rdoc.rdoc_files.include('README', 'CHANGELOG')
  rdoc.rdoc_files.include('lib/**/*.rb')
  rdoc.rdoc_files.exclude('lib/rails/generators/**/templates/*')
}

# Set available guide locales .....................................

locale_directory = "doc/guides/source/"
locale_name_patterns = [/\A[a-z]{2}\z/, /\A[a-z]{2}-[A-Z]{2}\z/]
available_locales = []

Dir.entries(locale_directory).each do |entry|
	if File.directory?(File.join(locale_directory, entry))
		for pattern in locale_name_patterns
			unless entry.scan(pattern).empty?
				available_locales << entry
			end
		end
	end
end

desc "Displays currently available guide locales"
task :guides_locales do
	unless available_locales.empty?
		puts "While the guides are generated in English by default, any of the following locales can be passed as an argument to 'rake guides' to obtain documentation in that locale:"
		for locale in available_locales
			puts "- " + locale
		end
	else
		puts "The guides are currently only available in English."
	end
end

# Generate GEM ----------------------------------------------------------------------------

spec = eval(File.read('railties.gemspec'))

Rake::GemPackageTask.new(spec) do |pkg|
  pkg.gem_spec = spec
end

# Publishing -------------------------------------------------------

desc "Release to gemcutter"
task :release => :package do
  require 'rake/gemcutter'
  Rake::Gemcutter::Tasks.new(spec).define
  Rake::Task['gem:push'].invoke
end

desc "Publish the guides"
task :pguides => :generate_guides do
  require 'rake/contrib/sshpublisher'
  mkdir_p 'pkg'
  `tar -czf pkg/guides.gz guides/output`
  path = "/home/apohllo/projects/home2/public/guides"
  Rake::SshFilePublisher.new("dragon.railsplayground.net", path, "pkg", "guides.gz").upload
  `ssh dragon.railsplayground.net 'cd #{path} && tar -xvzf guides.gz && rm -rf stylesheets && rm -rf javascripts && rm -rf images && mv guides/output/* . && rm -rf guides*'`
end
